agger: "2.0"
info:
  title: Esme
  description: This is an OpenAPI definition for the standard set of Open Banking
    (http://openbankingapis.io/) APIs from Esme.
  termsOfService: https://www.openbanking.org.uk/open-licence/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: 1.0.0
host: openapi.esmeloans.com
basePath: open-banking/v2.1/
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths:
  unsecured-sme-loans/:
    get:
      summary: Get Unsecured SME Loans
      description: This endpoint can contain multiple brands owned by a particular
        banking group
      operationId: pathOperation
      responses:
        200:
          description: OK
      tags:
      - ""
definitions:
  atms:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get
  branches:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get
  personal_current_accounts:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get
  business_current_accounts:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get
  unsecured_sme_loans:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get
  commercial_credit_cards:
    properties:
      meta:
        description: This is a default description.
        type: get
      data:
        description: This is a default description.
        type: get